<a href="https://colab.research.google.com/github/RoelJohnGuzman/58013-Linear-Algebra/blob/main/Activity_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

A = np.array([1,2,0])
B = np.array([3,1,-2])
C = np.array([0,0,1])

A+B+C

np.add(A,np.add(B,C))

np.sum(B)


2

In [ ]:
import numpy as np
np.subtract(A,B)

A-B


array([-2,  1,  2])

In [ ]:
import numpy as np
np.multiply(A,B)

A*B


array([3, 2, 0])

In [ ]:
import numpy as np
np.divide(A,B)

A/B

C = np.array([3.9,1.8,7.7])
D = np.array([1,1,1])
C//D

np.array(A/B,dtype=int)


array([0, 2, 0])