<a href="https://colab.research.google.com/github/RoelJohnGuzman/58013-Linear-Algebra/blob/main/Activity_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
X = np.array([
    [1,1,1],
    [3,-2,-1],
    [-1,4,2]
], dtype=float)
Y = np.array([
    [1],
    [4],
    [-3]
],dtype=float)
print(X)
print(X.shape)
print(Y)
print(Y.shape)


[[ 1.  1.  1.]
 [ 3. -2. -1.]
 [-1.  4.  2.]]
(3, 3)
[[ 1.]
 [ 4.]
 [-3.]]
(3, 1)


In [25]:
#([12500,18000,25700])

a = np.array([[30,10,120],[40,20,200],[50,40,360]])
a1 = np.array([[12500,10,120],[18000,20,200],[25700,40,360]])
a2 = np.array([[30,12500,120],[40,18000,200],[50,25700,360]])
a3 = np.array([[30,10,12500],[40,20,18000],[50,40,25700]])

y1 = np.linalg.det(a1)/np.linalg.det(a)
y2 = np.linalg.det(a2)/np.linalg.det(a)
y3 = np.linalg.det(a3)/np.linalg.det(a)

print("Flour per sack: ", y1)
print("Yeast per pack: ", y2)
print("Price of egg: ", y3)

Flour per sack:  329.99999999999784
Yeast per pack:  139.99999999999994
Price of egg:  10.000000000000242
