<a href="https://colab.research.google.com/github/RoelJohnGuzman/58013-Linear-Algebra/blob/main/Determinant_of_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
A = np.array([[4,7,8],[-9,0,0], [2,3,4]])
print(A)
round(np.linalg.det(A))

[[ 4  7  8]
 [-9  0  0]
 [ 2  3  4]]


36

In [3]:
import numpy as np
A = np.array([[2,3,-5],[7,1,-2], [-3,4,1]])
print(A)
round(np.linalg.det(A))

[[ 2  3 -5]
 [ 7  1 -2]
 [-3  4  1]]


-140

In [4]:
#ACTIVITY

import numpy as np
B = np.array([[1,2,-1],[4,6,-2], [-1,3,3]])
print(B)
round(np.linalg.det(B))

[[ 1  2 -1]
 [ 4  6 -2]
 [-1  3  3]]


-14