<a href="https://colab.research.google.com/github/RoelJohnGuzman/58013-Linear-Algebra/blob/main/Long%20quiz%201.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [45]:
#PROBLEM 1
import numpy as np

a = np.array ([[1,2,3],[4,5,6]])

b = np.array([[1,2],[3,4],[5,6]])

abresult = np.dot(a,b)
print("a.) \n" ,abresult, "\n" )


d1 = np.array([[1,2],[3,4]])
d2 = np.array([[1,2],[3,4]])
dresult = d1+d2
print("b.) \n", dresult,"\n")


c= np.array([[1,2,3],[4,5,6],[7,8,9]])
cresult = 2*c
print("c.) \n", cresult)

a.) 
 [[22 28]
 [49 64]] 

b.) 
 [[2 4]
 [6 8]] 

c.) 
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [44]:
#PROBLEM 2
import numpy as np

a = np.array([2,7,4])
b = np.array([3,9,8])

result = a[1]*b[2]-a[2]*b[1], a[2]*b[0]- a[0]*b[2], a[0]*b[1]- a[1]*b[0]

print("the cross product between A and B is",result)


the cross product between A and B is (20, -4, -3)
