<a href="https://colab.research.google.com/github/RoelJohnGuzman/58013-Linear-Algebra/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#Question 1. Create a Multiplication Table/Chart of 1 to 10 using numpy/ python program.
import numpy as np

i, j = 1, 10
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
while(i<=j):
    new_number = i*numbers
    print(new_number)
    i+=1

[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10 12 14 16 18 20]
[ 3  6  9 12 15 18 21 24 27 30]
[ 4  8 12 16 20 24 28 32 36 40]
[ 5 10 15 20 25 30 35 40 45 50]
[ 6 12 18 24 30 36 42 48 54 60]
[ 7 14 21 28 35 42 49 56 63 70]
[ 8 16 24 32 40 48 56 64 72 80]
[ 9 18 27 36 45 54 63 72 81 90]
[ 10  20  30  40  50  60  70  80  90 100]


In [4]:
#Question 2. In relation to Question 1, show a solution that doubles all the values of each element.
import numpy as np

i, j = 1, 10
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
while(i<=j):
    new_number = i*numbers
    double_number = new_number*2
    print(double_number)
    i+=1

[ 2  4  6  8 10 12 14 16 18 20]
[ 4  8 12 16 20 24 28 32 36 40]
[ 6 12 18 24 30 36 42 48 54 60]
[ 8 16 24 32 40 48 56 64 72 80]
[ 10  20  30  40  50  60  70  80  90 100]
[ 12  24  36  48  60  72  84  96 108 120]
[ 14  28  42  56  70  84  98 112 126 140]
[ 16  32  48  64  80  96 112 128 144 160]
[ 18  36  54  72  90 108 126 144 162 180]
[ 20  40  60  80 100 120 140 160 180 200]


In [2]:
#Question 3. Create a square matrix that has a diagonal 1's.
import numpy as np

a = np.array([[1,0,0],[0,1,0],[0,0,1]])
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [6]:
#Question 4. Type a python program that can view the size, shape, and dimension of the matrix above.
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

print("the shape is", matrix.shape)
print("the size is ", matrix.size)
print("the dimension is ", matrix.ndim)

the shape is (3, 4)
the size is  12
the dimension is  2


In [14]:
#Question 5.Create a result array by adding the following two NumPy arrays. Next, modify the result array by calculating the square of each element.
import numpy as np

arrayOne = np.array ([[5,6,9],[21,18,27]])
arrayTwo = np.array ([[15,33,24],[4,7,1]])

sumresult = np.add(arrayOne, arrayTwo)

print("the sum in \n ", sumresult, "\n")

squared = sumresult*sumresult

print("the squared of the sum is \n ", squared)




the sum in 
  [[20 39 33]
 [25 25 28]] 

the squared of the sum is 
  [[ 400 1521 1089]
 [ 625  625  784]]
