<a href="https://colab.research.google.com/github/RoelJohnGuzman/58013-Linear-Algebra/blob/main/Vector_spaces_and_operators.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

A = np.array([4,3])
B = np.array([2, -5])

print('Vector A is', A)
print('Vector B is', B)

Vector A is [4 3]
Vector B is [ 2 -5]


In [26]:
import numpy as np

ball1=np.array([[1],[2],[3]])
ball2=np.array([[0],[1],[-1]])
print(ball1)
print(ball2)

[[1]
 [2]
 [3]]
[[ 0]
 [ 1]
 [-1]]
(3, 1)


In [29]:
import numpy as np

ball1=np.array([1,2,3])
ball2=np.array([0,1,-1])
print(ball1)
print(ball2)
ball =np.shape(ball1)
balls =np.shape(ball2)
print(ball+balls)

[1 2 3]
[ 0  1 -1]
(3, 3)


In [36]:
import numpy as np

a = np.array([4,3])
b = np.array([2,-5])
r = np.add(a,b)
print(r)

[ 6 -2]


In [38]:
import numpy as np

a = np.array([4,3])
b = np.array([2,-5])
r = a+b
print(r)

[ 6 -2]


In [41]:
import numpy as np

r = np.subtract(a,b)
print(r)
q = np.subtract(b,a)
print(q)

[2 8]
[-2 -8]


In [54]:
import numpy as np

a=np.array([4,3])
s= np.array([2,-5])
v=s*a
print(v)

[  8 -15]


In [55]:
import numpy as np

a=np.array([4,3])
s= np.array([[2],[-5]])
v=s*a
print(v)

[[  8   6]
 [-20 -15]]


In [46]:
a = np.array([2,3])
b = np.array([1,7])

s=np.cross(a,b)
print(s)

11


In [58]:
import numpy as np

c = np.eye(3,3)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [63]:
import numpy as np

d=np.zeros([5,5])
print(d)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [65]:
import numpy as np

d=np.full([3,3],7)
print(d)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [68]:
import numpy as np

a=np.array([4,3])
s= np.array([[2],[-5]])
v=s*a
f=np.transpose(v)
print(f)

[[  8 -20]
 [  6 -15]]


In [70]:
import numpy as np

f=np.transpose(a)
print(f)

[4 3]
